Repository kangmingu01/EchoWorks, pull requests merged in 2024-07, with the labels that each got.

#1 test1
  Echo_Works/src/main/webapp/html/detail.html
Labels: enhancement

#5 테스트 이슈 - close#4
  .github/pull_request_template.md
  Echo_Works/src/main/webapp/index.jsp
Labels: 기능

#8 123
  Echo_Works/src/main/webapp/html/cart.html
Labels: 기능

#11 깃허브 연동 테스트
  Echo_Works/src/main/webapp/html/product.html
Labels: 기능

#12 테스트
  Echo_Works/src/main/webapp/html/mypage.html
Labels: 기능

#14 로그인, 회원가입, DB연동
  Echo_Works/src/main/java/echoworks/dao/MemberDAO.java
  Echo_Works/src/main/java/echoworks/dto/MemberDTO.java
  Echo_Works/src/main/java/echoworks/util/Utility.java
  Echo_Works/src/main/webapp/META-INF/context.xml
  Echo_Works/src/main/webapp/member/id_check.jsp
  Echo_Works/src/main/webapp/member/member_join.jsp
  Echo_Works/src/main/webapp/member/member_join_action.jsp
  Echo_Works/src/main/webapp/member/member_login.jsp
  Echo_Works/src/main/webapp/member/member_login_action.jsp
  Echo_Works/src/main/webapp/member/member_logout_action.jsp
Labels: 기능

#18 아이디, 비밀번호 찾기 구현 로그인>회원가입 넘어갈떄 오류수정 완료
  Echo_Works/src/main/java/echoworks/dao/MemberDAO.java
  Echo_Works/src/main/java/echoworks/util/Utility.java
  Echo_Works/src/main/webapp/cart/cart.jsp
  Echo_Works/src/main/webapp/member/idfind.jsp
  Echo_Works/src/main/webapp/member/idfind_action.jsp
  Echo_Works/src/main/webapp/member/member_join.jsp
  Echo_Works/src/main/webapp/member/member_login.jsp
  Echo_Works/src/main/webapp/member/passwordfind.jsp
  Echo_Works/src/main/webapp/member/passwordfind_action.jsp
  Echo_Works/src/main/webapp/member/terms.jsp
  Echo_Works/src/main/webapp/member/terms_action.jsp
  Echo_Works/src/main/webapp/payment/payment.jsp
Labels: 수정, 기능

#23 [KSH] product 파일생성
  Echo_Works/src/main/java/echoworks/dao/ProductDAO.java
  Echo_Works/src/main/java/echoworks/dto/ProductDTO.java
  Echo_Works/src/main/webapp/assets/img/kb_gb_1.jpg
  Echo_Works/src/main/webapp/assets/img/kb_gb_2.jpg
  Echo_Works/src/main/webapp/assets/img/kb_is_1.jpg
  Echo_Works/src/main/webapp/header.jsp
  Echo_Works/src/main/webapp/main_header.jsp
  Echo_Works/src/main/webapp/pd/product.jsp
Labels: 기능

#27 Khr login
  Echo_Works/src/main/webapp/member/idfind.jsp
  Echo_Works/src/main/webapp/member/member_join.jsp
  Echo_Works/src/main/webapp/member/member_login.jsp
  Echo_Works/src/main/webapp/member/passwordfind.jsp
  Echo_Works/src/main/webapp/member/terms.jsp
Labels: 버그
